version: '3.8'
services:
  api:
    volumes:
      # Mount the root folder that contains .git
      - .:/workspaces/:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"

  web:
    volumes:
      # Mount the root folder that contains .git
      - .:/workspaces/:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
